#!/usr/bin/env python3
"""Generate KERNEL 9 host adapters from one canonical source.

Reads governance/hosts.json plus the version in .claude-plugin/plugin.json and
emits, for every declared host:

  - the native plugin manifest
  - the native marketplace manifest
  - the lifecycle hook bindings, filtered to what that host actually supports
  - a truthful capability report

The point of generating rather than hand-maintaining these is that a host's
support surface is asserted exactly once. Kernel 8 hand-maintained a single
hooks.json and bound PostToolUseFailure unconditionally, which made it a silent
no-op on Codex with nothing anywhere saying so.

Modes:
    generate-adapters.py            # write the adapters
    generate-adapters.py --check    # exit 1 if any adapter is out of sync
"""

from __future__ import annotations

import argparse
import json
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HOSTS = os.path.join(REPO, "governance", "hosts.json")
CLAUDE_PLUGIN = os.path.join(REPO, ".claude-plugin", "plugin.json")

GENERATED_BANNER = "GENERATED by scripts/generate-adapters.py from governance/hosts.json. Do not edit by hand."


# --------------------------------------------------------------------------
# Canonical hook bindings.
#
# Declared once, in host-neutral form. Each binding names the lifecycle event it
# needs; the generator drops any binding whose event the target host does not
# implement, and the capability report says which ones were dropped and why.
# --------------------------------------------------------------------------

HOOK_BINDINGS = [
    {"event": "SessionStart", "matcher": "", "script": "session-start.sh", "timeout": 30,
     "statusMessage": "Loading KERNEL context..."},
    {"event": "PreToolUse", "matcher": "Write|Edit", "script": "detect-secrets.sh", "timeout": 5},
    {"event": "PermissionRequest", "matcher": "Bash", "script": "auto-approve-safe.sh", "timeout": 5},
    {"event": "UserPromptSubmit", "matcher": "", "script": "post-compact-restore.sh", "timeout": 5},
]


def load_json(path):
    with open(path) as fh:
        return json.load(fh)


def version() -> str:
    return load_json(CLAUDE_PLUGIN)["version"]


def plugin_root_var(host: dict) -> str:
    """The variable name this host substitutes in a hook command.

    Declared in governance/hosts.json, not chosen here. A name the host does
    not know expands to the empty string, so every hook runs an absolute path
    off / and exits 127. CODEX_PLUGIN_ROOT was invented in this function and
    killed every Codex hook until #191; keeping the value in the canonical
    source puts it under that file's evidence rule.
    """
    return "${%s}" % host["plugin_root_var"]


# --------------------------------------------------------------------------
# Builders
# --------------------------------------------------------------------------


def build_hooks(
    host_key: str, host: dict, root_override: str | None = None
) -> tuple[dict, list[str], list[tuple]]:
    """Return (hooks document, dropped bindings, bindings capped by a host ceiling).

    root_override pins the plugin-root variable when the document is shared between
    hosts. Without it the same hook is emitted once per host spelling and every hook
    in the shared file runs twice, which is what the first attempt at this did.
    """
    supported = set(host["supported_lifecycle_events"])
    root = root_override or plugin_root_var(host)

    grouped: dict[str, list] = {}
    dropped: list[str] = []
    capped: list[tuple] = []

    for binding in HOOK_BINDINGS:
        event = binding["event"]
        if event not in supported:
            dropped.append(f"{event}:{binding['script']}")
            continue

        # Never declare a timeout the host will overrule. Codex hard-clamps
        # SessionEnd to 3s and warns on every session start; asking for 210
        # bought a truncated hook and a warning, not time. Emitting the real
        # ceiling makes the manifest say what will actually happen.
        ceiling = host.get("hook_timeout_ceilings_seconds", {}).get(event)
        timeout = binding["timeout"]
        if ceiling is not None and timeout > ceiling:
            capped.append((event, binding["script"], timeout, ceiling))
            timeout = ceiling

        entry = {
            "type": "command",
            "command": f"{root}/hooks/scripts/{binding['script']}",
            "timeout": timeout,
        }
        if "statusMessage" in binding:
            entry["statusMessage"] = binding["statusMessage"]

        # Same event + same matcher share one group, matching both hosts' schema.
        bucket = grouped.setdefault(event, [])
        for existing in bucket:
            if existing["matcher"] == binding["matcher"]:
                existing["hooks"].append(entry)
                break
        else:
            bucket.append({"matcher": binding["matcher"], "hooks": [entry]})

    return {"hooks": grouped}, dropped, capped


def merge_hooks(target: dict, doc: dict) -> dict:
    """Union one host's bindings into a shared manifest, keeping the larger timeout.

    The larger value is correct because a ceiling is enforced by the host at
    runtime, not by us: Codex clamps SessionEnd to 3s and says so, while Claude
    Code needs the full 210s for the session-end batch commit. Emitting 3 to spare
    one warning would silently truncate the other host's hook.
    """
    for event, groups in doc["hooks"].items():
        bucket = target["hooks"].setdefault(event, [])
        for group in groups:
            for existing in bucket:
                if existing["matcher"] == group["matcher"]:
                    slot = existing
                    break
            else:
                slot = {"matcher": group["matcher"], "hooks": []}
                bucket.append(slot)
            for entry in group["hooks"]:
                for have in slot["hooks"]:
                    if have["command"] == entry["command"]:
                        have["timeout"] = max(have["timeout"], entry["timeout"])
                        break
                else:
                    slot["hooks"].append(dict(entry))
    return target


def build_plugin_manifest(host_key: str, host: dict, spec: dict) -> dict:
    base = load_json(CLAUDE_PLUGIN)
    manifest = {
        "name": "kernel",
        "version": version(),
        "description": spec["interface"]["longDescription"],
        "author": base.get("author", {"name": "Aria Han"}),
        "homepage": base.get("homepage"),
        "repository": base.get("repository"),
        "license": base.get("license", "MIT"),
        "keywords": [
            "claude-code", "codex", "plugin", "hooks", "guardrails",
            "agent-memory", "agentdb", "verification", "auto-mode", "safety",
            "adaptive-execution", "memory", "orchestration", "handoff", "methodology",
        ],
    }

    if host_key == "codex":
        # Codex declares skills explicitly and carries a richer interface block.
        manifest["skills"] = "./skills/"
        manifest["interface"] = dict(spec["interface"])

    return manifest


def build_marketplace(host_key: str, host: dict, spec: dict) -> dict:
    desc = spec["interface"]["shortDescription"]

    if host_key == "claude":
        return {
            "name": "kernel-marketplace",
            "description": desc,
            "owner": {"name": "Aria Han"},
            "plugins": [
                {"name": "kernel", "source": "./", "description": desc, "version": version()}
            ],
        }

    return {
        "name": "kernel-marketplace",
        "interface": {"displayName": spec["interface"]["displayName"]},
        "plugins": [
            {
                "name": "kernel",
                "source": {"source": "local", "path": "./"},
                # `authentication` is omitted deliberately. Codex 0.145.0 accepts
                # only ON_INSTALL or ON_USE and rejects the whole marketplace file
                # for anything else; there is no "none" variant. Kernel needs no
                # auth, so the field is left off. Verified live: `codex plugin
                # marketplace add` rejected authentication:"NONE" and accepted
                # the manifest once the key was dropped.
                "policy": {"installation": "AVAILABLE"},
                "category": spec["interface"]["category"],
            }
        ],
    }


def build_capability_report(spec: dict) -> str:
    """A truthful, generated statement of what each host actually supports."""
    wanted = spec["kernel_lifecycle_bindings"]
    lines = [
        "# KERNEL host capability report",
        "",
        f"<!-- {GENERATED_BANNER} -->",
        "",
        "What each host actually supports. Kernel does not claim parity it does not have.",
        "",
        "| Lifecycle event Kernel binds | " + " | ".join(
            spec["hosts"][h]["display_name"] for h in spec["hosts"]
        ) + " |",
        "|---" * (len(spec["hosts"]) + 1) + "|",
    ]

    for event in wanted:
        row = [event]
        for host in spec["hosts"].values():
            if event not in host["supported_lifecycle_events"]:
                row.append("**no**")
                continue
            # "Supported" and "supported with a ceiling that truncates our
            # binding" are different claims. A flat yes hid the second one.
            ceiling = host.get("hook_timeout_ceilings_seconds", {}).get(event)
            row.append("yes" if ceiling is None else f"yes, capped at {ceiling}s")
        lines.append("| " + " | ".join(row) + " |")

    lines += ["", "## Host-enforced timeout ceilings", ""]
    any_ceiling = False
    for host in spec["hosts"].values():
        ceilings = host.get("hook_timeout_ceilings_seconds", {})
        if not ceilings:
            continue
        any_ceiling = True
        lines += [f"### {host['display_name']}", ""]
        for event, limit in sorted(ceilings.items()):
            wanted_timeout = max(
                (b["timeout"] for b in HOOK_BINDINGS if b["event"] == event), default=None
            )
            asked = f" Kernel's binding wants {wanted_timeout}s." if wanted_timeout else ""
            lines.append(f"- **{event}** — capped at {limit}s.{asked}")
        lines += ["", host.get("hook_timeout_ceiling_evidence", ""), ""]
    if not any_ceiling:
        lines += ["No host-enforced ceilings recorded.", ""]

    lines += ["## Unsupported features, and what degrades", ""]
    any_gap = False
    for key, host in spec["hosts"].items():
        gaps = host.get("unsupported_lifecycle_events", {})
        if not gaps:
            continue
        any_gap = True
        lines.append(f"### {host['display_name']}")
        lines.append("")
        for event, why in gaps.items():
            lines.append(f"- **{event}** — {why}")
        lines.append("")
    if not any_gap:
        lines.append("No gaps recorded.")
        lines.append("")

    lines += ["## Adapter targets", ""]
    for key, host in spec["hosts"].items():
        lines += [
            f"### {host['display_name']} (`{key}`)",
            "",
            f"- instruction file: `{host['instruction_file']}`",
            f"- plugin manifest: `{host['plugin_manifest']}`",
            f"- marketplace manifest: `{host['marketplace_manifest']}`",
            f"- hook bindings written to: `{host['hooks_file']}`",
            f"- skill invocation: `{host['invoke_prefix']}<name>`",
        ]
        # Operator-facing truths that are not derivable from the paths above.
        # A host can decline to read the file Kernel writes, refuse to run hooks
        # until a flag is set, or require per-hook approval. Each is a silent
        # failure if it is not stated here.
        for field, label in (
            ("hooks_file_note", "hook bindings actually read from"),
            ("hooks_declaration_note", "manifest declaration"),
            ("hooks_feature_flag", "hooks feature flag"),
            ("project_hook_trust", "project hook trust"),
            ("lifecycle_events_evidence", "lifecycle evidence"),
            ("agents_support", "agents"),
        ):
            if host.get(field):
                lines.append(f"- {label}: {host[field]}")
        lines += [
            f"- verified by: {host['verified_by']}",
            f"- verified on: {host['verified_on']}",
            "",
        ]

    # Callers add the one canonical trailing newline. Avoid emitting a blank
    # line at EOF, which `git diff --check` correctly reports as generated drift.
    return "\n".join(lines).rstrip("\n")


# --------------------------------------------------------------------------
# Emit
# --------------------------------------------------------------------------


def targets(spec: dict) -> dict[str, str]:
    """Map of relative path -> desired file content."""
    out: dict[str, str] = {}

    # ONE hooks manifest, shared. Codex does not read a per-host file: it reads
    # hooks/hooks.json, the same one Claude Code reads, and it says so itself in
    # two places. Its startup warning names that path when it clamps a timeout,
    # and its own trust store keys our hooks as
    # `kernel@kernel-marketplace:hooks/hooks.json:<event>:<group>:<index>`.
    #
    # We shipped a second, Codex-tuned manifest at the repo root for months. It was
    # never loaded, so its corrections never took effect: #199 fixed a SessionEnd
    # timeout there and the warning it was meant to silence kept firing every
    # session. Pointing Codex at it with a `hooks` key in .codex-plugin/plugin.json
    # measurably makes things worse, not better -- with the key declared, a
    # PostToolUse hook that fires without it stopped firing at all (A/B, rows per
    # apply_patch went 1 -> 0 -> 0 -> 1 on removal).
    #
    # So hosts sharing a path share a document, built as the union of their
    # bindings with the largest declared timeout. A host that does not implement an
    # event ignores it (Codex has read PostToolUseFailure here all along), and a
    # host with a ceiling clamps at runtime and says so. What each host will
    # actually do with the shared file is reported in HOST-CAPABILITIES.md, which
    # is where a per-host difference belongs: in the record, not in a file nobody
    # reads.
    shared_hooks: dict[str, dict] = {}

    for host_key, host in spec["hosts"].items():
        hooks_doc, _dropped, _capped = build_hooks(
            host_key, host, root_override="${%s}" % spec["shared_plugin_root_var"]
        )
        merge_hooks(shared_hooks.setdefault(host["hooks_file"], {"hooks": {}}), hooks_doc)
        out[host["plugin_manifest"]] = (
            json.dumps(build_plugin_manifest(host_key, host, spec), indent=2) + "\n"
        )
        out[host["marketplace_manifest"]] = (
            json.dumps(build_marketplace(host_key, host, spec), indent=2) + "\n"
        )

    for path, doc in shared_hooks.items():
        out[path] = json.dumps(doc, indent=2) + "\n"

    out[os.path.join("docs", "kernel-9", "HOST-CAPABILITIES.md")] = (
        build_capability_report(spec) + "\n"
    )
    return out


def main(argv=None):
    ap = argparse.ArgumentParser(description="Generate KERNEL host adapters.")
    ap.add_argument("--check", action="store_true", help="verify sync without writing")
    args = ap.parse_args(argv)

    spec = load_json(HOSTS)
    desired = targets(spec)

    drift = []
    for rel, content in sorted(desired.items()):
        path = os.path.join(REPO, rel)
        current = None
        if os.path.exists(path):
            with open(path) as fh:
                current = fh.read()

        if current == content:
            continue

        if args.check:
            drift.append(rel)
        else:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w") as fh:
                fh.write(content)
            print(f"wrote {rel}")

    if args.check:
        if drift:
            print("adapters out of sync with governance/hosts.json:", file=sys.stderr)
            for rel in drift:
                print(f"  {rel}", file=sys.stderr)
            print("\nrun: scripts/generate-adapters.py", file=sys.stderr)
            return 1
        print(f"all {len(desired)} generated adapters are in sync")

    return 0


if __name__ == "__main__":
    sys.exit(main())
